# # ----------- Build Vite React App -----------
# FROM node:20 AS build

# WORKDIR /app
# COPY package*.json ./
# RUN npm install

# COPY . .
# RUN npm run build

# # ----------- Production Stage -----------
# FROM nginx:alpine

# COPY nginx.conf /etc/nginx/conf.d/default.conf
# COPY --from=build /app/dist /usr/share/nginx/html

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

# ----------- Build Vite React App -----------
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

# 👇 THIS IS THE FIX (MOST IMPORTANT LINE)
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY . .
RUN npm run build

# ----------- Production Stage -----------
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
